image:
  file: .gitpod.Dockerfile
tasks:
  - name: init
    init: >
      npm install;
  - name: npmstart
    command: >
      export TZ="Asia/Tokyo";
      export URL=`gp url 8080`;
      eval $(gp env -e) ;
      npm run start;
 